#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  2 07:43:57 2023

@author: sreekrishnaravishankar
"""

import math
import numpy as np
import matplotlib.pyplot as plt
from CoolProp.CoolProp import PropsSI as cp

def Enthalpy(P,T):
    H = cp('Hmass', 'P', P, 'T', T, 'Hydrogen')
    return H

def Energy_Eqn(h_x,G,rho_x):
    h0 = h_x + ((G**2)/2*rho_x)
    return h0
def Mometum_Eqn(P_x,G,rho_x):
    P0 = P_x+((G**2)/rho_x)
    return P0

P_x = 18.11e5
Mdot = 37.962
D = 15e-2
A_pipe = (math.pi)*(D**2)/4
G = Mdot/A_pipe
T_x = 167.38
rho_x = cp('D', 'P', P_x, 'T', T_x, 'Hydrogen')
h_x = Enthalpy(P_x, T_x)
h0 = Energy_Eqn(h_x, G, rho_x)
P0 = Mometum_Eqn(P_x, G, rho_x)
T0 = cp('T', 'P', P0, 'Hmass', h0, 'Hydrogen')
